Nytt endepunkt for flex
navikt/medlemskap-sykepengerlytter pull request #82
Opened 2023-05-31 10:59 UTC by hjmNav

2023-05-31 11:16 UTC, x10an14-nav requested changes
Småplukk, lgtm =)

2023-05-31 11:16 UTC, x10an14-nav commented on src/main/kotlin/no/nav/medlemskap/sykepenger/lytter/config/Configuration.kt
> +        "AZURE_APP_TENANT_ID" to "966ac572-f5b7-4bbe-aa88-c76419c0f851",
```suggestion
        "AZURE_APP_TENANT_ID" to "",
```

Er dette en nøkkel?

"Er bare i dev" -> tenker det fortsatt er verdt å ikke pushe det, plutselig glemmer man seg og pusher en nøkkel til et dev-miljø som bruker maskerte/skarpe data (og ikke bare syntetiske).
Mange nok slike om dagen mens fss fortsatt er en ting.

2023-05-31 11:16 UTC, x10an14-nav commented on src/main/kotlin/no/nav/medlemskap/sykepenger/lytter/nais/SykepengerLytterRoutes.kt
> +
```suggestion

```

Fjerne tom linje?

2023-05-31 11:16 UTC, x10an14-nav commented on src/main/kotlin/no/nav/medlemskap/sykepenger/lytter/nais/SykepengerLytterRoutes.kt
> +           val  requiredVariables:Map<String,String> = getRequiredVariables(call.request)
```suggestion
           val  requiredVariables:Map<String,String> = getRequiredVariables(call.request) // Map<String, String> kan fint endres senere
```

2023-05-31 11:16 UTC, x10an14-nav commented on src/main/kotlin/no/nav/medlemskap/sykepenger/lytter/nais/SykepengerLytterRoutes.kt
> +}
```suggestion
    }
}
```

2023-05-31 11:16 UTC, x10an14-nav commented on src/main/kotlin/no/nav/medlemskap/sykepenger/lytter/nais/SykepengerLytterRoutes.kt
> +    val headers = setOf("fnr")
```suggestion
    val headers = setOf("fnr") // Hard-coded value(s) we want to ensure are present
```

2023-05-31 11:16 UTC, x10an14-nav commented on src/main/kotlin/no/nav/medlemskap/sykepenger/lytter/nais/SykepengerLytterRoutes.kt
> +    for (variabel in queryParams ){
```suggestion
    val queryParams = setOf("fom","tom") // Hard-coded value(s) we want to ensure are present
    for (variabel in queryParams ){
```

Flytt variabler til nærmest der de brukes, vi lever ikke i C lenger hvor alle variabler ligger på topp av funksjonen og må manuelt huskes på avh. hvilken linje i funksjonen man er =P

2023-05-31 11:16 UTC, x10an14-nav commented on src/main/kotlin/no/nav/medlemskap/sykepenger/lytter/nais/SykepengerLytterRoutes.kt
> +        throw BadRequestException("Header '$variabel' mangler")
```suggestion
            throw BadRequestException("Header '$variabel' mangler")
```

2023-05-31 11:16 UTC, x10an14-nav commented on src/main/kotlin/no/nav/medlemskap/sykepenger/lytter/nais/SykepengerLytterRoutes.kt
> +    val queryParams = setOf("fom","tom")
```suggestion
```

Ref. nedenfor forslag:
> Flytt variabler til nærmest der de brukes, vi lever ikke i C lenger hvor alle variabler ligger på topp av funksjonen og må manuelt huskes på avh. hvilken linje i funksjonen man er =P

2023-06-06 09:53 UTC, hjmNav commented on src/main/kotlin/no/nav/medlemskap/sykepenger/lytter/config/Configuration.kt
> +        "AZURE_APP_TENANT_ID" to "966ac572-f5b7-4bbe-aa88-c76419c0f851",
dett er en identifikasjon på applikasjon og er ikke sensitiv info. Denne må deles når man eksempelvis skal hente ut et token mot en annen tjeneste en sin egen.. Kan fjerne den da den ligger embedded på server, men det betyr at jeg ikke kan kjøre kode lokalt. frem til vi løser lokalt nais miljø så lar jeg den bli som i dag

2023-06-13 13:42 UTC, merged